######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 22 13:08:35 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += loginwindow.h networkclient.h timerwindow.h
FORMS += loginwindow.ui timerwindow.ui
SOURCES += loginwindow.cpp main.cpp networkclient.cpp timerwindow.cpp
RESOURCES += libki.qrc
